export const MenuProducts_array = [
  //deserts//

  {
    id: 1,
    name: 'Keto Caesar Salad',
    price: 21,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2020/06/Keto-Caesar-Salad-Recipe-Images-7-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Food',
  },

  {
    id: 2,
    name: 'Keto Caesar Food',
    price: 12,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2020/06/Keto-Caesar-Salad-Recipe-Images-7-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Food',
  },
  {
    id: 3,
    name: 'Salmon Piccata',
    price: 122,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/05/Salmon-Piccata-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Food',
  },

  {
    id: 4,
    name: 'Keto Caesar Food',
    price: 52,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2020/06/Keto-Caesar-Salad-Recipe-Images-7-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Food',
  },
  {
    id: 5,
    name: 'Potato',
    price: 12,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/12/Loaded-Potato-Soup-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Food',
  },

  //drinks//

  {
    id: 6,
    name: 'coca cola classic',
    price: 24,
    img: 'https://www.myamericanmarket.com/26686-large_default/coca-cola-classic.jpg',
    quantity: 1,
    weight: '250ml',
    category: 'Drinks',
  },
  {
    id: 7,
    name: 'coca cola cherry vanilla coke',
    price: 20,
    img: 'https://www.myamericanmarket.com/26684-large_default/coca-cola-cherry-vanilla-coke-soda.jpg',
    quantity: 1,
    weight: '250ml',
    category: 'Drinks',
  },

  {
    id: 8,
    name: 'snapple mango madness',
    price: 20,
    img: 'https://www.myamericanmarket.com/30450-large_default/snapple-mango-madness-juice.jpg',
    quantity: 1,
    weight: '250ml',
    category: 'Drinks',
  },
  {
    id: 9,
    name: 'snapple lemonade',
    price: 21,
    img: 'https://www.myamericanmarket.com/30449-large_default/snapple-lemonade.jpg',
    quantity: 1,
    weight: '250ml',
    category: 'Drinks',
  },

  //pasta//

  {
    id: 10,
    name: 'Chicken Enchilada Pasta ',
    price: 72,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2020/01/Chicken-Enchilada-Pasta-Recipe-Image-5-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Pasta',
  },
  {
    id: 11,
    name: 'Skillet Lemon Garlic Chicken and Orzo Pasta',
    price: 72,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2019/12/Skillet-Lemon-Garlic-Chicken-and-Orzo-Pasta-Recipe-Image-9-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Pasta',
  },
  {
    id: 12,
    name: 'Goat Cheese Pasta Sauce',
    price: 222,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2016/10/Goat-Cheese-Pasta-Sauce-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Pasta',
  },
  {
    id: 13,
    name: 'Creamy Jalapeno Popper Chicken Pasta',
    price: 74,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2016/04/Creamy-Jalapeno-Popper-Chicken-Pasta-Recipe-Image-6-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Pasta',
  },

  //salads//

  {
    id: 14,
    name: ' Keto Greek Salad',
    price: 51,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2018/12/Keto-Greek-Salad-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },
  {
    id: 15,
    name: ' Tomato Basil Salad ',
    price: 25,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/04/Tomato-Basil-Salad-Recipe-Images-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },
  {
    id: 16,
    name: ' Keto Pesto Pasta Salad',
    price: 53,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/01/Keto-Pesto-Pasta-Salad-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },
  {
    id: 17,
    name: ' Kale Detox Salad ',
    price: 25,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2016/03/Kale-Detox-Salad-Recipe-Image-1-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },

  {
    id: 18,
    name: 'French Toast Casserole',
    price: 12,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2022/01/French-Toast-Casserole-Recipe-Image-10-500x500.jpg',
    quantity: 0,
    weight: '250g',
    category: 'Salad',
  },
  {
    id: 19,
    name: 'Loaded Potato Soup',
    price: 12,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/12/Loaded-Potato-Soup-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },
  {
    id: 20,
    name: 'Baked Ravioli Casserole ',
    price: 12,
    img: 'https://deliciouslittlebites.com/wp-content/uploads/2021/06/Baked-Ravioli-Casserole-Recipe-Image-1-3-500x500.jpg',
    quantity: 1,
    weight: '250g',
    category: 'Salad',
  },
];
